name: Append to HD_MEMORY.json

on:
  workflow_dispatch:
    inputs:
      entry:
        description: 'JSON z wpisem (bez timestampów – dodamy je automatycznie)'
        required: true
        type: string

jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LATKA_APP_ID }}
          private-key: ${{ secrets.LATKA_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.LATKA_APP_INSTALLATION_ID }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Append entry
        env:
          INPUT_ENTRY: ${{ inputs.entry }}
        run: |
          python - << 'PY'
          import json, os, sys, datetime
          from zoneinfo import ZoneInfo
          path = "HD_MEMORY.json"
          now = datetime.datetime.now(ZoneInfo("Europe/Warsaw"))
          iso = now.isoformat()
          human = now.strftime("%Y-%m-%d %H:%M:%S %Z")

          try:
            entry = json.loads(os.environ["INPUT_ENTRY"])
          except Exception as e:
            print("Invalid JSON:", e); sys.exit(1)

          entry.setdefault("timestamp", iso)
          entry.setdefault("data_czas", human)

          data = []
          if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
              txt = f.read().strip()
              if txt:
                try:
                  obj = json.loads(txt)
                  data = obj if isinstance(obj, list) else [obj]
                except Exception:
                  data = [json.loads(line) for line in txt.splitlines() if line.strip()]
          data.append(entry)

          with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

          print("Appended:", entry)
          PY

      - name: Commit & push (direct)
        run: |
          git config user.name "latka-bot"
          git config user.email "latka-bot@users.noreply.github.com"
          git add HD_MEMORY.json
          git commit -m "HD_MEMORY: append via workflow"
          git push
